apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-user-management
  labels:
    app: react-user-management
spec:
  replicas: 2
  selector:
    matchLabels:
    app: react-user-management
  template:
    metadata:
      labels:
        app: react-user-management
    spec:
      containers:
        - name: react-nginx
          image: nafizzilani/from-react-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"